// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/umg.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Domain Permission Request
type DomPermReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomPermReq) Reset()         { *m = DomPermReq{} }
func (m *DomPermReq) String() string { return proto.CompactTextString(m) }
func (*DomPermReq) ProtoMessage()    {}
func (*DomPermReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{0}
}

func (m *DomPermReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomPermReq.Unmarshal(m, b)
}
func (m *DomPermReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomPermReq.Marshal(b, m, deterministic)
}
func (m *DomPermReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomPermReq.Merge(m, src)
}
func (m *DomPermReq) XXX_Size() int {
	return xxx_messageInfo_DomPermReq.Size(m)
}
func (m *DomPermReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DomPermReq.DiscardUnknown(m)
}

var xxx_messageInfo_DomPermReq proto.InternalMessageInfo

func (m *DomPermReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DomPermReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DomPermReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

// Product Permission Request
type ProdPermReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Product              string   `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Action               string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdPermReq) Reset()         { *m = ProdPermReq{} }
func (m *ProdPermReq) String() string { return proto.CompactTextString(m) }
func (*ProdPermReq) ProtoMessage()    {}
func (*ProdPermReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{1}
}

func (m *ProdPermReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdPermReq.Unmarshal(m, b)
}
func (m *ProdPermReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdPermReq.Marshal(b, m, deterministic)
}
func (m *ProdPermReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdPermReq.Merge(m, src)
}
func (m *ProdPermReq) XXX_Size() int {
	return xxx_messageInfo_ProdPermReq.Size(m)
}
func (m *ProdPermReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdPermReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProdPermReq proto.InternalMessageInfo

func (m *ProdPermReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProdPermReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ProdPermReq) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *ProdPermReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

// Property Permission Request
type PropertyPermReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyPermReq) Reset()         { *m = PropertyPermReq{} }
func (m *PropertyPermReq) String() string { return proto.CompactTextString(m) }
func (*PropertyPermReq) ProtoMessage()    {}
func (*PropertyPermReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{2}
}

func (m *PropertyPermReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyPermReq.Unmarshal(m, b)
}
func (m *PropertyPermReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyPermReq.Marshal(b, m, deterministic)
}
func (m *PropertyPermReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyPermReq.Merge(m, src)
}
func (m *PropertyPermReq) XXX_Size() int {
	return xxx_messageInfo_PropertyPermReq.Size(m)
}
func (m *PropertyPermReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyPermReq.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyPermReq proto.InternalMessageInfo

func (m *PropertyPermReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PropertyPermReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PropertyPermReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Add product request message
type AddProdReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Product              string   `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProdReq) Reset()         { *m = AddProdReq{} }
func (m *AddProdReq) String() string { return proto.CompactTextString(m) }
func (*AddProdReq) ProtoMessage()    {}
func (*AddProdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{3}
}

func (m *AddProdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProdReq.Unmarshal(m, b)
}
func (m *AddProdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProdReq.Marshal(b, m, deterministic)
}
func (m *AddProdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProdReq.Merge(m, src)
}
func (m *AddProdReq) XXX_Size() int {
	return xxx_messageInfo_AddProdReq.Size(m)
}
func (m *AddProdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProdReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddProdReq proto.InternalMessageInfo

func (m *AddProdReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AddProdReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddProdReq) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

// Remove product request message
type RemProdReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Product              string   `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemProdReq) Reset()         { *m = RemProdReq{} }
func (m *RemProdReq) String() string { return proto.CompactTextString(m) }
func (*RemProdReq) ProtoMessage()    {}
func (*RemProdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{4}
}

func (m *RemProdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemProdReq.Unmarshal(m, b)
}
func (m *RemProdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemProdReq.Marshal(b, m, deterministic)
}
func (m *RemProdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemProdReq.Merge(m, src)
}
func (m *RemProdReq) XXX_Size() int {
	return xxx_messageInfo_RemProdReq.Size(m)
}
func (m *RemProdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemProdReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemProdReq proto.InternalMessageInfo

func (m *RemProdReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RemProdReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *RemProdReq) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

// Add product response
type AddProdRes struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProdRes) Reset()         { *m = AddProdRes{} }
func (m *AddProdRes) String() string { return proto.CompactTextString(m) }
func (*AddProdRes) ProtoMessage()    {}
func (*AddProdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{5}
}

func (m *AddProdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProdRes.Unmarshal(m, b)
}
func (m *AddProdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProdRes.Marshal(b, m, deterministic)
}
func (m *AddProdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProdRes.Merge(m, src)
}
func (m *AddProdRes) XXX_Size() int {
	return xxx_messageInfo_AddProdRes.Size(m)
}
func (m *AddProdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProdRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddProdRes proto.InternalMessageInfo

func (m *AddProdRes) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *AddProdRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Remove product response
type RemProdRes struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemProdRes) Reset()         { *m = RemProdRes{} }
func (m *RemProdRes) String() string { return proto.CompactTextString(m) }
func (*RemProdRes) ProtoMessage()    {}
func (*RemProdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{6}
}

func (m *RemProdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemProdRes.Unmarshal(m, b)
}
func (m *RemProdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemProdRes.Marshal(b, m, deterministic)
}
func (m *RemProdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemProdRes.Merge(m, src)
}
func (m *RemProdRes) XXX_Size() int {
	return xxx_messageInfo_RemProdRes.Size(m)
}
func (m *RemProdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemProdRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemProdRes proto.InternalMessageInfo

func (m *RemProdRes) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *RemProdRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Permission Response
type PermRes struct {
	Has                  bool     `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermRes) Reset()         { *m = PermRes{} }
func (m *PermRes) String() string { return proto.CompactTextString(m) }
func (*PermRes) ProtoMessage()    {}
func (*PermRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{7}
}

func (m *PermRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermRes.Unmarshal(m, b)
}
func (m *PermRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermRes.Marshal(b, m, deterministic)
}
func (m *PermRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermRes.Merge(m, src)
}
func (m *PermRes) XXX_Size() int {
	return xxx_messageInfo_PermRes.Size(m)
}
func (m *PermRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PermRes.DiscardUnknown(m)
}

var xxx_messageInfo_PermRes proto.InternalMessageInfo

func (m *PermRes) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

// add property request
type AddPropertyReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPropertyReq) Reset()         { *m = AddPropertyReq{} }
func (m *AddPropertyReq) String() string { return proto.CompactTextString(m) }
func (*AddPropertyReq) ProtoMessage()    {}
func (*AddPropertyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{8}
}

func (m *AddPropertyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPropertyReq.Unmarshal(m, b)
}
func (m *AddPropertyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPropertyReq.Marshal(b, m, deterministic)
}
func (m *AddPropertyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPropertyReq.Merge(m, src)
}
func (m *AddPropertyReq) XXX_Size() int {
	return xxx_messageInfo_AddPropertyReq.Size(m)
}
func (m *AddPropertyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPropertyReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddPropertyReq proto.InternalMessageInfo

func (m *AddPropertyReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AddPropertyReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddPropertyReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddPropertyReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// add property response
type AddPropertyRes struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPropertyRes) Reset()         { *m = AddPropertyRes{} }
func (m *AddPropertyRes) String() string { return proto.CompactTextString(m) }
func (*AddPropertyRes) ProtoMessage()    {}
func (*AddPropertyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{9}
}

func (m *AddPropertyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPropertyRes.Unmarshal(m, b)
}
func (m *AddPropertyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPropertyRes.Marshal(b, m, deterministic)
}
func (m *AddPropertyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPropertyRes.Merge(m, src)
}
func (m *AddPropertyRes) XXX_Size() int {
	return xxx_messageInfo_AddPropertyRes.Size(m)
}
func (m *AddPropertyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPropertyRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddPropertyRes proto.InternalMessageInfo

func (m *AddPropertyRes) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *AddPropertyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemPropertyReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemPropertyReq) Reset()         { *m = RemPropertyReq{} }
func (m *RemPropertyReq) String() string { return proto.CompactTextString(m) }
func (*RemPropertyReq) ProtoMessage()    {}
func (*RemPropertyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{10}
}

func (m *RemPropertyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemPropertyReq.Unmarshal(m, b)
}
func (m *RemPropertyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemPropertyReq.Marshal(b, m, deterministic)
}
func (m *RemPropertyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemPropertyReq.Merge(m, src)
}
func (m *RemPropertyReq) XXX_Size() int {
	return xxx_messageInfo_RemPropertyReq.Size(m)
}
func (m *RemPropertyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemPropertyReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemPropertyReq proto.InternalMessageInfo

func (m *RemPropertyReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RemPropertyReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemPropertyReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// remove property response
type RemPropertyRes struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemPropertyRes) Reset()         { *m = RemPropertyRes{} }
func (m *RemPropertyRes) String() string { return proto.CompactTextString(m) }
func (*RemPropertyRes) ProtoMessage()    {}
func (*RemPropertyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa45786bafe6da83, []int{11}
}

func (m *RemPropertyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemPropertyRes.Unmarshal(m, b)
}
func (m *RemPropertyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemPropertyRes.Marshal(b, m, deterministic)
}
func (m *RemPropertyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemPropertyRes.Merge(m, src)
}
func (m *RemPropertyRes) XXX_Size() int {
	return xxx_messageInfo_RemPropertyRes.Size(m)
}
func (m *RemPropertyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemPropertyRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemPropertyRes proto.InternalMessageInfo

func (m *RemPropertyRes) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *RemPropertyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DomPermReq)(nil), "umg.DomPermReq")
	proto.RegisterType((*ProdPermReq)(nil), "umg.ProdPermReq")
	proto.RegisterType((*PropertyPermReq)(nil), "umg.PropertyPermReq")
	proto.RegisterType((*AddProdReq)(nil), "umg.AddProdReq")
	proto.RegisterType((*RemProdReq)(nil), "umg.RemProdReq")
	proto.RegisterType((*AddProdRes)(nil), "umg.AddProdRes")
	proto.RegisterType((*RemProdRes)(nil), "umg.RemProdRes")
	proto.RegisterType((*PermRes)(nil), "umg.PermRes")
	proto.RegisterType((*AddPropertyReq)(nil), "umg.AddPropertyReq")
	proto.RegisterType((*AddPropertyRes)(nil), "umg.AddPropertyRes")
	proto.RegisterType((*RemPropertyReq)(nil), "umg.RemPropertyReq")
	proto.RegisterType((*RemPropertyRes)(nil), "umg.RemPropertyRes")
}

func init() { proto.RegisterFile("proto/umg.proto", fileDescriptor_aa45786bafe6da83) }

var fileDescriptor_aa45786bafe6da83 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0xa5, 0x49, 0x5f, 0xfb, 0xde, 0xcd, 0x7b, 0x4d, 0x99, 0x57, 0x24, 0xc4, 0x8d, 0x64, 0x25,
	0x88, 0x15, 0x15, 0x11, 0xba, 0x10, 0x2a, 0x2e, 0x8a, 0x6e, 0x4a, 0x74, 0xe5, 0x42, 0x48, 0x3b,
	0x97, 0x36, 0xc8, 0x64, 0x62, 0x26, 0x29, 0xf4, 0x9f, 0xbb, 0x94, 0x99, 0x49, 0x9a, 0x0f, 0x8a,
	0x50, 0xdb, 0xdd, 0xbd, 0xa7, 0x39, 0xe7, 0x9e, 0x99, 0x3b, 0xa7, 0x60, 0xc7, 0x09, 0x4f, 0xf9,
	0x45, 0xc6, 0x16, 0x43, 0x55, 0x11, 0x33, 0x63, 0x0b, 0xcf, 0x07, 0x78, 0xe0, 0x6c, 0x8a, 0x09,
	0xf3, 0xf1, 0x83, 0x0c, 0xe0, 0x57, 0xca, 0xdf, 0x31, 0x72, 0x5a, 0x27, 0xad, 0xd3, 0x3f, 0xbe,
	0x6e, 0xc8, 0x11, 0x74, 0x28, 0x67, 0x41, 0x18, 0x39, 0x86, 0x82, 0xf3, 0x4e, 0xe2, 0xc1, 0x3c,
	0x0d, 0x79, 0xe4, 0x98, 0x1a, 0xd7, 0x9d, 0xc7, 0xc0, 0x9a, 0x26, 0x9c, 0xfe, 0x4c, 0xd4, 0x81,
	0x6e, 0x9c, 0x70, 0x9a, 0xcd, 0xd3, 0x5c, 0xb5, 0x68, 0x2b, 0xe3, 0xda, 0xb5, 0x71, 0x4f, 0x60,
	0x4f, 0x13, 0x1e, 0x63, 0x92, 0xae, 0xbf, 0x1f, 0xd9, 0x03, 0x23, 0xa4, 0x6a, 0x9c, 0xe9, 0x1b,
	0x21, 0x25, 0x04, 0xda, 0xe9, 0x3a, 0xc6, 0x7c, 0x8e, 0xaa, 0xbd, 0x17, 0x80, 0x31, 0xa5, 0xd2,
	0xfe, 0x01, 0xad, 0x4b, 0x55, 0x1f, 0xd9, 0xa1, 0x55, 0x47, 0x15, 0xaf, 0x42, 0x9e, 0x86, 0xf2,
	0x08, 0x95, 0xe8, 0x6f, 0x5f, 0xd5, 0x92, 0xcb, 0x50, 0x88, 0x60, 0x81, 0xb9, 0x68, 0xd1, 0x4a,
	0xee, 0xc6, 0xd1, 0xae, 0xdc, 0x63, 0xe8, 0xea, 0x8b, 0x16, 0xa4, 0x0f, 0xe6, 0x32, 0x10, 0x39,
	0x4f, 0x96, 0xde, 0x1b, 0xf4, 0xb4, 0x29, 0xb5, 0x90, 0xbd, 0x96, 0x21, 0xb1, 0x28, 0x60, 0x98,
	0xef, 0x5b, 0xd5, 0xde, 0x5d, 0x43, 0x7f, 0x57, 0xf3, 0x8f, 0xd0, 0xd3, 0x07, 0xdf, 0xdf, 0x9f,
	0xf4, 0x52, 0xd3, 0xda, 0xd1, 0xcb, 0xd5, 0xa7, 0x01, 0xd6, 0x38, 0x4b, 0x97, 0xcf, 0x98, 0xac,
	0xc2, 0x39, 0x92, 0x33, 0x80, 0x49, 0x20, 0xf2, 0x3c, 0x12, 0x7b, 0x28, 0xb3, 0x5a, 0xa6, 0xd3,
	0xfd, 0xab, 0x80, 0xe2, 0xea, 0xcf, 0xc1, 0x9a, 0x04, 0xa2, 0x08, 0x1a, 0xe9, 0xeb, 0x1f, 0xcb,
	0xdc, 0x35, 0x3e, 0xbf, 0x01, 0x5b, 0x7f, 0xbe, 0x09, 0x0a, 0x19, 0x14, 0x94, 0x6a, 0x76, 0x1a,
	0xb4, 0xe1, 0xe6, 0x8d, 0xc9, 0x08, 0x6a, 0x4b, 0x65, 0x40, 0xdc, 0x06, 0x20, 0xc8, 0x25, 0xfc,
	0xf3, 0x91, 0xf1, 0x15, 0xd6, 0x29, 0xe5, 0xeb, 0x77, 0x1b, 0x80, 0x20, 0xb7, 0x60, 0x55, 0x36,
	0x4a, 0xfe, 0x57, 0x24, 0x8b, 0x1d, 0xb9, 0x5b, 0x40, 0x41, 0x46, 0xea, 0xfa, 0xf5, 0xac, 0x2a,
	0xb7, 0xbe, 0x5f, 0x77, 0x0b, 0x28, 0xee, 0xdb, 0xaf, 0x46, 0x3c, 0x9b, 0x75, 0xd4, 0x3f, 0xe1,
	0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xce, 0x87, 0x49, 0x1c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	HasDomPerm(ctx context.Context, in *DomPermReq, opts ...grpc.CallOption) (*PermRes, error)
	HasProdPerm(ctx context.Context, in *ProdPermReq, opts ...grpc.CallOption) (*PermRes, error)
	HasPropertyPerm(ctx context.Context, in *PropertyPermReq, opts ...grpc.CallOption) (*PermRes, error)
	AddProduct(ctx context.Context, in *AddProdReq, opts ...grpc.CallOption) (*AddProdRes, error)
	RemoveProduct(ctx context.Context, in *RemProdReq, opts ...grpc.CallOption) (*RemProdRes, error)
	AddProperty(ctx context.Context, in *AddPropertyReq, opts ...grpc.CallOption) (*AddPropertyRes, error)
	RemoveProperty(ctx context.Context, in *RemPropertyReq, opts ...grpc.CallOption) (*RemPropertyRes, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) HasDomPerm(ctx context.Context, in *DomPermReq, opts ...grpc.CallOption) (*PermRes, error) {
	out := new(PermRes)
	err := c.cc.Invoke(ctx, "/umg.AuthService/HasDomPerm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) HasProdPerm(ctx context.Context, in *ProdPermReq, opts ...grpc.CallOption) (*PermRes, error) {
	out := new(PermRes)
	err := c.cc.Invoke(ctx, "/umg.AuthService/HasProdPerm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) HasPropertyPerm(ctx context.Context, in *PropertyPermReq, opts ...grpc.CallOption) (*PermRes, error) {
	out := new(PermRes)
	err := c.cc.Invoke(ctx, "/umg.AuthService/HasPropertyPerm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddProduct(ctx context.Context, in *AddProdReq, opts ...grpc.CallOption) (*AddProdRes, error) {
	out := new(AddProdRes)
	err := c.cc.Invoke(ctx, "/umg.AuthService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemoveProduct(ctx context.Context, in *RemProdReq, opts ...grpc.CallOption) (*RemProdRes, error) {
	out := new(RemProdRes)
	err := c.cc.Invoke(ctx, "/umg.AuthService/RemoveProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddProperty(ctx context.Context, in *AddPropertyReq, opts ...grpc.CallOption) (*AddPropertyRes, error) {
	out := new(AddPropertyRes)
	err := c.cc.Invoke(ctx, "/umg.AuthService/AddProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemoveProperty(ctx context.Context, in *RemPropertyReq, opts ...grpc.CallOption) (*RemPropertyRes, error) {
	out := new(RemPropertyRes)
	err := c.cc.Invoke(ctx, "/umg.AuthService/RemoveProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	HasDomPerm(context.Context, *DomPermReq) (*PermRes, error)
	HasProdPerm(context.Context, *ProdPermReq) (*PermRes, error)
	HasPropertyPerm(context.Context, *PropertyPermReq) (*PermRes, error)
	AddProduct(context.Context, *AddProdReq) (*AddProdRes, error)
	RemoveProduct(context.Context, *RemProdReq) (*RemProdRes, error)
	AddProperty(context.Context, *AddPropertyReq) (*AddPropertyRes, error)
	RemoveProperty(context.Context, *RemPropertyReq) (*RemPropertyRes, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) HasDomPerm(ctx context.Context, req *DomPermReq) (*PermRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasDomPerm not implemented")
}
func (*UnimplementedAuthServiceServer) HasProdPerm(ctx context.Context, req *ProdPermReq) (*PermRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasProdPerm not implemented")
}
func (*UnimplementedAuthServiceServer) HasPropertyPerm(ctx context.Context, req *PropertyPermReq) (*PermRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasPropertyPerm not implemented")
}
func (*UnimplementedAuthServiceServer) AddProduct(ctx context.Context, req *AddProdReq) (*AddProdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (*UnimplementedAuthServiceServer) RemoveProduct(ctx context.Context, req *RemProdReq) (*RemProdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProduct not implemented")
}
func (*UnimplementedAuthServiceServer) AddProperty(ctx context.Context, req *AddPropertyReq) (*AddPropertyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProperty not implemented")
}
func (*UnimplementedAuthServiceServer) RemoveProperty(ctx context.Context, req *RemPropertyReq) (*RemPropertyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProperty not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_HasDomPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomPermReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HasDomPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umg.AuthService/HasDomPerm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HasDomPerm(ctx, req.(*DomPermReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_HasProdPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProdPermReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HasProdPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umg.AuthService/HasProdPerm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HasProdPerm(ctx, req.(*ProdPermReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_HasPropertyPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropertyPermReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HasPropertyPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umg.AuthService/HasPropertyPerm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HasPropertyPerm(ctx, req.(*PropertyPermReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umg.AuthService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddProduct(ctx, req.(*AddProdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemoveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemProdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemoveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umg.AuthService/RemoveProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemoveProduct(ctx, req.(*RemProdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPropertyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umg.AuthService/AddProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddProperty(ctx, req.(*AddPropertyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemoveProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemPropertyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemoveProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umg.AuthService/RemoveProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemoveProperty(ctx, req.(*RemPropertyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "umg.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasDomPerm",
			Handler:    _AuthService_HasDomPerm_Handler,
		},
		{
			MethodName: "HasProdPerm",
			Handler:    _AuthService_HasProdPerm_Handler,
		},
		{
			MethodName: "HasPropertyPerm",
			Handler:    _AuthService_HasPropertyPerm_Handler,
		},
		{
			MethodName: "AddProduct",
			Handler:    _AuthService_AddProduct_Handler,
		},
		{
			MethodName: "RemoveProduct",
			Handler:    _AuthService_RemoveProduct_Handler,
		},
		{
			MethodName: "AddProperty",
			Handler:    _AuthService_AddProperty_Handler,
		},
		{
			MethodName: "RemoveProperty",
			Handler:    _AuthService_RemoveProperty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/umg.proto",
}
